### ISSUE TITLE
FrontEnd - Things ToDo

### ISSUE THREAD

**Issue by SaharaSheik** [Face-Recognition-App-SD/Face-Recognition-Mobile#91]
-Camera:
- [x]  Put a frame on camera

-Admin 
- [x] Admin Create Users
- [x] Admin Delete Users
- [x] Admin Modify Users
- [x] Admin Create patients regardless of if they have created patient or not
- [x] Admin Delete patients regardless of if they have created patient or not
- [x] Admin Modify patients regardless of if they have created patient or not
- [x] Admin Can View All Users
- [x] Admin Can View All patients
- [x] Admin Can use Use Face Verify On patients 
- [ ] Admin Can use Use Face Verify On users
- [x] Admin Can use Use Face Recognition On patients
- [ ] Admin Can use Use Face Recognition On Users
- [x] Admin to activate and deactivate user 
- [x] Admin to Search patients (search with ID, Search with name, Search with last Name).  Search should  be dynamic as they type patients show up (so if they type for example jo both john and joAnn show up)
- [x] Admin to Search User  (search with ID, Search with name, Search with last Name).  Search should  be dynamic as they type patients show up
- [ ] Admin to add upload image for users

-User
- [ ] Forget Password 
- [x] Search patients (search with ID, Search with name, Search with last Name).  Search should  be dynamic as they type patients show up (so if they type for example jo both john and joAnn show up)

**Comment by nguyendo3004** [comment]
Bug list need to fix

- [ ] when a regular user tries to log in to admin site, she/he can't login and display a notify about their permission
